<!-- Copyright (c) Trieflow LLC. Licensed under the MIT License. -->
<Project>
  <PropertyGroup>
    <_FileQuayNuGetRoot>$([MSBuild]::EnsureTrailingSlash('$(NuGetPackageRoot)'))</_FileQuayNuGetRoot>
    <FileQuayRuntimeVersion>10.0.12</FileQuayRuntimeVersion>
    <SelfContained>true</SelfContained>
    <PublishSelfContained>true</PublishSelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <UseAppHost>true</UseAppHost>
    <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="$(_FileQuayNuGetRoot)microsoft.netcore.app.runtime.win-$(Platform)\$(FileQuayRuntimeVersion)\LICENSE.TXT" Link="Licenses\DotNetRuntime\LICENSE.TXT" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="$(_FileQuayNuGetRoot)microsoft.netcore.app.runtime.win-$(Platform)\$(FileQuayRuntimeVersion)\THIRD-PARTY-NOTICES.TXT" Link="Licenses\DotNetRuntime\THIRD-PARTY-NOTICES.TXT" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Condition="'$(UseWinUI)' == 'true'" Include="$(_FileQuayNuGetRoot)microsoft.windowsdesktop.app.runtime.win-$(Platform)\$(FileQuayRuntimeVersion)\LICENSE" Link="Licenses\WindowsDesktop\LICENSE" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
